version: "3.3"
services:
    auto-rsa:
        container_name: auto-rsa
        image: docker.io/nelsondane/auto-rsa:latest
        # build: . # uncomment this line if you want to build the image locally with docker-compose up -d --build
        restart: unless-stopped
        env_file:
            - .env
        tty: true
        labels:
            com.centurylinklabs.watchtower.enable: "true"

    watchtower:
        image: containrrr/watchtower
        command: --cleanup --label-enable --interval 3600
        container_name: Watchtower
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        labels:
            com.centurylinklabs.watchtower.enable: "true"
        restart: unless-stopped
