name: Docker Push

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/auto-rsa:latest
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/auto-rsa:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/auto-rsa:buildcache,mode=max
