name: Docker Build and Push

on:
  push:
    branches:
      - 'main'
      - 'develop*'

jobs:
  call-workflow-dockerhub-build-push:
    uses: NelsonDane/Custom-GitHub-Actions/.github/workflows/docker-registry-build-push.yml@581e863f75f5f7d003be1060f9f0811533e9387b
    with:
      image_name: auto-rsa
      image_tag: ${{ github.ref_name == 'main' && 'latest' || startsWith(github.ref_name, 'develop') && github.ref_name }}
      should_push: ${{ github.ref_name == 'main' || startsWith(github.ref_name, 'develop') }}
      platforms: linux/amd64,linux/arm64
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
