name: Docker Build and Push

on:
  push:
    branches:
      - 'main'
      - 'develop*'

jobs:
  call-workflow-dockerhub-build-push:
    uses: NelsonDane/Custom-GitHub-Actions/.github/workflows/docker-registry-build-push.yml@ac3c1faf566a202b50264debfc6e5d9ff37c6ce4
    with:
      image_name: auto-rsa
      image_tag: ${{ github.ref_name == 'main' && 'latest' || startsWith(github.ref_name, 'develop') && github.ref_name }}
      should_push: ${{ github.ref_name == 'main' || startsWith(github.ref_name, 'develop') }}
      platforms: linux/amd64,linux/arm64
    secrets:
      DOCKER_REGISTRY_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKER_REGISTRY_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
